### ISSUE TITLE
Transaction fees computed wrong in GUI for assets, causing inability to send transfer

### ISSUE THREAD

**Issue by dnotestein** [BitShares/qt_wallet#104]
If I try to transfer an asset such as TRADE.BTC (a user-issued asset), the GUI thinks I need .1 TRADE.BTC to make the transfer. In actuality, I need .1 BTS to send the transfer. Because of this miscalculation, I'm unable to transfer TRADE.BTC, since I don't have enough TRADE.BTC to satisfy GUI. This is a high priority error for gateway testing.
Note that I am able to send the desired amount via the console of the GUI, so this is just a GUI calculation issue.

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/600

**Comment by jcalfee** [comment]
Here is a review:  The wallet will query `wallet_get_transaction_fee <desired asset>` where the desired asset is the asset being transferred.  The asset that is returned by the RPC command is the asset that is shown in the GUI as the fee.  

If there is not enough to pay in that asset, the bitshares_client will go looking for other assets that can pay the fee.  How will the wallet know what fee to display to the user before they confirm the transfer?

Also: If the asset being transferred has a balance in any market pegged asset that has enough active price feeds, that would probably be a good fee to return and to accept.  It may be an option for Dan to get price feeds published for TRADE.BTC to make it easier to transfer.
