### ISSUE TITLE
Don't show tray icon and have close window button to exit the application (except OS X)

### ISSUE THREAD

**Issue by valzav** [BitShares/qt_wallet#108]
All modern OS (Ubuntu, Windows 8.X, OS X) have a pretty compact taskbar that shows only application icons, so users just minimize the apps if they want them continue to run. Having the close button to hide application windows is counter intuitive at least on Ubuntu and Windows. Also on Ubuntu due to a bug the tray icon is shown in the top right corner of the screen. Also Windows hides new tray icons by default so users might not even know that BitShares client is still running and consume resources, probably this explains why some of them still use old 0.4.x versions.

**Comment by vikramrajkumar** [comment]
Related: #93

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/qt_wallet/commit/d0fc812a6690f3451d902039960092ffa36cbed6
