### ISSUE TITLE
invalid asset amount error when voting

### ISSUE THREAD

**Issue by fortaleza** [BitShares/qt_wallet#115]
Windows 7, version 0.9.1
In the GUI, when I go to one of my accounts and then navigate to the "Vote" tab and press the "Vote" button the voting process fails with this error:
invalid asset amount (35005)

getStackTrace@app.js:30:5176
 ○ request@app.js:36:12339
 ○ transfer@app.js:37:4796
 ○ m@app.js:30:19786
 ○ ok@app.js:31:7850
 ○ app.js:8:7986
 ○ e@app.js:8:14415
 ○ $eval@app.js:6:83428
 ○ $apply@app.js:6:83659
 ○ app.js:8:14472
 ○ dispatch@app.js:3:14478
 ○ handle@app.js:3:11253
35005 invalid_asset_amount: invalid asset amount

    {"share_string":"1939.4623900000001","max_rhs_size":5}
    bitshares  asset_record.cpp:93 bts::blockchain::asset_record::share_string_to_satoshi

    {"share_string":"1939.4623900000001","precision":100000}
    bitshares  asset_record.cpp:109 bts::blockchain::asset_record::share_string_to_satoshi

    {"amount":"1939.4623900000001"}
    bitshares  asset_record.cpp:114 bts::blockchain::asset_record::asset_from_string

    {"amount":"1939.4623900000001","symbol":"BTS"}
    bitshares  chain_interface.cpp:241 bts::blockchain::chain_interface::to_ugly_asset

    {"amount_to_transfer":"1939.4623900000001","asset_symbol":"BTS","from_account_name":"gringoy","recipient":"gringoy","memo_message":"vote_all","strategy":"vote_all"}
    bitshares  wallet_api.cpp:322 bts::client::detail::client_impl::wallet_transfer

    {}
    bitshares  common_api_client.cpp:3845 bts::rpc_stubs::common_api_client::wallet_transfer

**Comment by vikramrajkumar** [comment]
Duplicate: https://github.com/BitShares/web_wallet/issues/681
