### ISSUE TITLE
Re-indexing progress percentage on splash getting stuck on Windows & Linux

### ISSUE THREAD

**Issue by bitsha256** [BitShares/qt_wallet#29]

**Comment by theoreticalbts** [comment]
The Qt UI still doesn't show any progress indicator when re-indexing.

**Comment by vikramrajkumar** [comment]
@theoreticalbts What platform? The indicator on the splash screen has been showing up fine for me on all releases when testing on Mac.

**Comment by theoreticalbts** [comment]
There is a progress bar, but the actual symptom is the progress bar not moving, stuck at 3% for ~30 minutes required to complete reindexing.  (Sorry, I'm filing this ticket on behalf of someone else and there was a miscommunication.)

**Comment by theoreticalbts** [comment]
Platform:  Windows, but I am told that Linux does the same thing.

**Comment by nathanhourt** [comment]
What progress bar? There has never been a progress bar for reindexing...

**Comment by dnotestein** [comment]
probably they're talking about the sync up progress shown on status bar at bottom of GUI. It definitely doesn't update at a reasonable rate: I always go to the console to find out the real sync progress, it's pretty bad...

**Comment by valzav** [comment]
What do you mean by "doesn't update at a reasonable rate"? It should be get updated every 10 seconds.

**Comment by vikramrajkumar** [comment]
I can't find any progress bars; I assume this is referring only to the reindexing percentage on the splash not updating.

**Comment by nathanhourt** [comment]
I've never seen that get stuck. It goes slow, sure, but it updates at every percentage...

**Comment by dnotestein** [comment]
@valzav , maybe it is 10s, I don't know. It "felt" to me like it just wasn't updating properly, but it's possible it was just my expectation of more rapid update notices. IMO, 10s is too long for updates on sync status. There's not much I can do with the client until it syncs, so I feel much more comfortable when I see it making progress towards that goal. Maybe reduce it to 3s? The only speed limit on the update rate as far as I'm concerned is just readability.

**Comment by valzav** [comment]
We are planning to have a splash screen with a progress bar while it syncing, I'll make progress bar updates more frequent.

**Comment by nathanhourt** [comment]
The splash screen does not update every 10s. It updates every time the percentage completion changes. This is all done in C++, and there's really no way to strap a web GUI onto this part of the startup process, as the RPC system hasn't started yet at this point.

**Comment by vikramrajkumar** [comment]
I believe the original issue posted by @theoreticalbts is that the splash screen percentage indicator is freezing.

@valzav and @dnotestein are talking about the sync progress at the bottom of the web interface, which is a separate issue.

**Comment by vikramrajkumar** [comment]
Not enough info; closing.
