### ISSUE TITLE
Support OS X 10.10 dark mode icons

### ISSUE THREAD

**Issue by valzav** [BitShares/qt_wallet#75]
@robrigo: Currently when using the wallet on OS X 10.10 with dark mode enabled, the bitshares icon in the top bar isn't visible (black icon on black top bar).

http://www.leebrimelow.com/prepping-icons-for-yosemite-dark-mode/

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/qt_wallet/commit/d0fc812a6690f3451d902039960092ffa36cbed6
