### ISSUE TITLE
error encountered with cmake recommended "out of source"  build

### ISSUE THREAD

**Issue by crazybits** [BitShares/qt_wallet#88]
i issued the following command with the cmake  recommended "out of source" build
mkdir build&& cd build&&cmake ..
make

the following error was encountered, any idea?

[ 93%] Built target buildweb
make[2]: *** No rule to make target `programs/qt_wallet/images/splash_screen.jpg', needed by `programs/qt_wallet/qrc_bitshares.cpp'.  Stop.
make[1]: *** [programs/qt_wallet/CMakeFiles/BitShares.dir/all] Error 2
make: *** [all] Error 2

**Comment by valzav** [comment]
Yes, there is an issue with out of source build - you need to copy splash_screen.jpg from src dir to your build's programs/qt_wallet/images/

**Comment by crazybits** [comment]
i copied the whole programs/qt_wallet/images/ folder  to /build/programs/qt_wallet/ but another issue encountered as below, how can i update the cmake file  to enable the "out of source“ build?


make[2]: *** No rule to make target `../programs/qt_wallet/htdocs/blank.html', needed by `programs/qt_wallet/qrc_htdocs.cpp'.  Stop.
make[1]: *** [programs/qt_wallet/CMakeFiles/BitShares.dir/all] Error 2

**Comment by valzav** [comment]
You need htdocs populated. Read web_wallet's readme and use lineman to generate the files.

**Comment by crazybits** [comment]
actually, i have modified the  bitshares\programs\qt_wallet\GenerateHtDocs.cmake.in to copy the htdocs to the build path bitshares\build\programs\qt_wallet\htdocs, but problem persists

**Comment by vikramrajkumar** [comment]
Is this fixed by https://github.com/BitShares/qt_wallet/commit/089b969152cd78f99794e1417e217a3ea312d7b4?

**Comment by crazybits** [comment]
@vikramrajkumar  yes, issue fixed with pulling the mentioned commit, issue closed.
