### ISSUE TITLE
24h volume wrong in Market menu overview

### ISSUE THREAD

**Issue by tramker** [BitShares/qt_wallet#91]
24h volume as shown in featured markets overview in WIndows client is wrong. For example BitUSD shows 5,600,000 BitUSD while it should be 560,000 BTS.

Also I think the price pair text should be reversed. Currently it shows 96.00000 BTS/BitUSD, which interpreted as 96 BTS per USD is right, but by Forex standards, it shoud be 96 BitUSD/BTS or 0.01042 BTS/BitUSD. I suggest presenting it like this:
24h volume: 5,6M BTS
BitUSD/BTS: 96
BTS/BitUSD: 0.01042

**Comment by vikramrajkumar** [comment]
Moved: https://github.com/BitShares/web_wallet/issues/527
