### ISSUE TITLE
splash screen disappears on click

### ISSUE THREAD

**Issue by vikramrajkumar** [BitShares/qt_wallet#92]
y

**Comment by nathanhourt** [comment]
See http://doc.qt.io/qt-5/qsplashscreen.html#details:
*The user can hide the splash screen by clicking on it with the mouse.*

We can probably turn this behavior off if so desired.

**Comment by emfrias** [comment]
I vote for turning it off (at least until the main window pops up).  It's confusing when you accidentally click on the splash screen while it's reindexing the chain database; you're left with no indication that BitShares is running.

**Comment by vikramrajkumar** [comment]
Does the splash screen show the reindexing status? Or is it the main window? If it is the splash screen, we should keep it but not let it disappear.

**Comment by emfrias** [comment]
the splash screen shows the reindexing status.  Normally what happens to me is it starts reindexing, I go read my mail or do something else for a while, then click back on the splash screen window to see how far along it is, and that's when it disappears.
