### ISSUE TITLE
Wallet doesn't display again after double clicking on tray icon

### ISSUE THREAD

**Issue by dnotestein** [BitShares/qt_wallet#93]
On Windows, at least, if you minimize the wallet to the tray, then double click on the tray icon, the wallet should become visible again. Instead, it only shows up as a button on the taskbar, which must be further clicked in order to display the wallet. This is also very subtle, so it often feels like you've clicked on the tray icon and nothing has happened.

**Comment by vikramrajkumar** [comment]
https://github.com/BitShares/qt_wallet/commit/d0fc812a6690f3451d902039960092ffa36cbed6
