### ISSUE TITLE
master branch build failed: ClientWrapper.cpp:146:95: error: too many arguments to function call

### ISSUE THREAD

**Issue by valzav** [BitShares/qt_wallet#98]
Building CXX object programs/qt_wallet/CMakeFiles/BitShares.dir/BitSharesApp.cpp.o
/Users/vz/bts/bitshares-prod/programs/qt_wallet/ClientWrapper.cpp:146:95: error: too many arguments to function call, expected at most 3, have 4
      _client->open( data_dir.toStdWString(), fc::optional<fc::path>(), fc::optional<bool>(), [=](float progress) {
      ~~~~~~~~~~~~~                                                                           ^~~~~~~~~~~~~~~~~~~~~

**Comment by vikramrajkumar** [comment]
@valzav Are you using the correct submodule version of qt_wallet?

**Comment by valzav** [comment]
I'm using qt wallet directly without submodule

**Comment by vikramrajkumar** [comment]
bitshares `master` branch should use qt_wallet `b40cbecefeb0ba62d1ab5e625ff19d1701803712`, newer commits won't work

**Comment by valzav** [comment]
thank you, this helped
