### ISSUE TITLE
How to prevent crashing of wallet.dat ?

### ISSUE THREAD

**Issue by DclickT** [BitShares/qt_wallet#99]
When I run my premine-qt application on Ubuntu 14.04, it always give me Error message. I don't know what is the problem every time I am getting this and I'm very much frustrated with that. Actually I developing new coin. How I can resolve this.

and error is 

"Error initializing block database.
Do you want to rebuild the block database now?"

**Comment by vikramrajkumar** [comment]
It sounds like you are talking about PTS--which is obsolete has been upgraded to DPOS: https://github.com/PTS-DPOS/PTS

There is no mining in BitShares.
